kmpmd/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url( r'^propdesk/', include( 'propdesk.urls' )),
]

propdesk/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = 'propdesk'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^(?P<portfolio_id>[0-9]+)/$', views.portview, name="portview"),
    url(r'^prop/(?P<property_id>[0-9]+)/$', views.prop, name="prop"),
    url(r'^$', views.index, name='index'),
    url(r'^project/new/$', views.project_new, name='project_new'),
    url(r'^tenant/new/$', views.tenant_new, name='tenant_new'),
    url(r'^vendor/new/$', views.vendor_new, name='vendor_new'),
    url(r'^search/$', views.search, name='search'),
]

propdesk/models.py
from django.db import models
from datetime import datetime, date

class City (models.Model):
    city_name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.city_name


class Portfolio(models.Model):
    portfolio_name = models.CharField(max_length=20,  unique=True)
    city = models.ForeignKey(City, on_delete=models.CASCADE)

    def __str__(self):
        return self.portfolio_name


class Property (models.Model):
    portfolio = models.ForeignKey(Portfolio, on_delete=models.CASCADE)
    prop_name = models.CharField(max_length=250, unique=True)
    property_sf = models.FloatField()
    property_address = models.CharField(max_length=100)
    property_city = models.CharField(max_length=100)
    property_state = models.CharField(max_length=100)
    property_zip = models.CharField(max_length=100)
    def __str__(self):
        return self.prop_name


class Tenant (models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    tenant_name = models.CharField(max_length=100)
    tenant_emergency_name = models.CharField(max_length=100)
    tenant_emergency_email = models.CharField(max_length=100)
    tenant_emergency_phone = models.CharField(max_length=100)
    tenant_site_name = models.CharField(max_length=100)
    tenant_site_email = models.CharField(max_length=100)
    tenant_site_phone = models.CharField(max_length=100)
    def __str__(self):
        return self.tenant_name


class Vendor (models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    vendor_name = models.CharField(max_length=100)
    vendor_contact = models.CharField(max_length=100)
    vendor_email = models.CharField(max_length=100)
    vendor_phone = models.CharField(max_length=100)


class Owner (models.Model):
    owner_name = models.CharField(max_length=100, unique=True)
    def __str__(self):
        return self.owner_name


class Project (models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE, blank=True, null=True)
    portfolio = models.ForeignKey(Portfolio, on_delete=models.CASCADE, blank=True, null=True)
    tenant = models.ForeignKey(Tenant, blank=True, null=True)
    type = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    startdate = models.DateField(null=True)
    contractcomplete = models.NullBooleanField(default=False, blank=True, null=True)
    enddate = models.DateField(null=True)
    invoicestatus = models.CharField(max_length=100, blank=True, null=True)
    cmfeestatus = models.CharField(max_length=100, blank=True, null=True)
    def __str__(self):
        return self.name

propdesk/forms.py
from django import forms
from .models import Project, Tenant, Vendor


class ProjectForm(forms.ModelForm):

    class Meta:
        model = Project
        fields = ('property', 'portfolio', 'tenant', 'type', 'name', 'startdate', 'contractcomplete', 'enddate', 'invoicestatus', 'cmfeestatus')


class TenantForm(forms.ModelForm):

    class Meta:
        model = Tenant
        fields = ('property', 'tenant_name', 'tenant_emergency_name', 'tenant_emergency_email', 'tenant_emergency_phone', 'tenant_site_name', 'tenant_site_email', 'tenant_site_phone')

class VendorForm(forms.ModelForm):

    class Meta:
        model = Vendor
        fields = ('property', 'vendor_name', 'vendor_contact', 'vendor_email', 'vendor_phone')

propdesk/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse
from .models import Property, City, Portfolio
from .forms import ProjectForm, VendorForm, TenantForm
import operator
from django.db.models import Q

def index(request):
    all_cities = City.objects.prefetch_related('portfolio_set').all()
    context = {
        'all_cities': all_cities,
    }
    return render(request, 'propdesk/index.html', context)


def portview(request, portfolio_id):
    portfolio = get_object_or_404(Portfolio, pk=portfolio_id)
    return render(request, 'propdesk/portview.html', {'portfolio': portfolio })


def prop(request, property_id):
    property = get_object_or_404(Property, pk=property_id)
    property_related = Property.objects.prefetch_related('property_set').all()
    return render(request, 'propdesk/prop.html', {'property': property, 'property_related': property_related })


def project_new(request):
    if request.method == "POST":
        form = ProjectForm(request.POST)
        if form.is_valid():
            project = form.save(commit=False)
            project.save()
    else:
        form = ProjectForm()
    return render(request, 'propdesk/project_new.html', {'form': form})


def tenant_new(request):
    if request.method == "POST":
        form = TenantForm(request.POST)
        if form.is_valid():
            tenant = form.save(commit=False)
            tenant.save()
    else:
        form = TenantForm()
    return render(request, 'propdesk/tenant_new.html', {'form': form})


def vendor_new(request):
    if request.method == "POST":
        form = VendorForm(request.POST)
        if form.is_valid():
            vendor = form.save(commit=False)
            vendor.save()
    else:
        form = VendorForm()
    return render(request, 'propdesk/vendor_new.html', {'form': form})


def search(request):
    if 'q' in request.GET and request.GET['q']:
        q = request.GET['q']
        properties = Property.objects.filter(prop_name__icontains=q)
        return render(request, 'propdesk/search_results.html',
            {'properties': properties, 'query': q})
    else:
        return HttpResponse('Please submit a search term.')

propdesk/templates/propdesk/base.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Waynes Wild Web</title>
    <script src="https://use.fontawesome.com/bccccab0e8.js"></script>
    <link rel="stylesheet" href="{% static 'propdesk/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'propdesk/style.css' %}" />
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'propdesk/jquery-3.1.0.min.js' %}"></script>
    <script src="{% static 'propdesk/site.js' %}"></script>
</head>
<body>
{% include 'propdesk/nav.html' %}


            {% block content %}
            {% endblock %}

</body>
</html>

propdesk/templates/propdesk/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Waynes Wild Web</title>
    <link rel="stylesheet" href="{% static 'propdesk/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'propdesk/style.css' %}" />
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'propdesk/jquery-3.1.0.min.js' %}"></script>
    <script src="{% static 'propdesk/site.js' %}"></script>
</head>
<body>
  {% include 'propdesk/nav.html' %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">Portfolios</div>
                <div class="panel-body">
                    <ul class="list-group">
                        {% for city in all_cities %}
                        <li class="list-group-item">
                            <h3>{{ city.city_name }}</h3>
                            <div class="list-group">
                                {% for a in city.portfolio_set.all %}
                                 <a class="list-group-item listitem mainlist"href="{% url 'propdesk:portview' a.id %}">  {{a.portfolio_name}} </a>
                                {% endfor %}
                            </div>

                        </li>

                        {% endfor %}

                    </ul>
                </div>

            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-primary">
                <div class="panel-heading">Statistics</div>
                <div class="panel-body">
                    <ul class="list-group">
                        {% for city in all_cities %}
                        <li class="list-group-item mainlist">
                            <h3>{{ city.city_name }}</h3>
                            <p> Maybe # of properties?</p>
                            <p> Maybe % of each property type?</p>
                            <p>Total square footage?</p>
                            </li>
                        {% endfor %}

                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

propdesk/templates/propdesk/nav.html
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid" id="navfluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigationbar">
       <span class="sr-only">Toggle navigation</span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
      </button>
        <a class="navbar-brand" href="{% url 'propdesk:index' %}">KMPM Desktop</a>
      </div>

      <div class="collapse navbar-collapse" id="navigationbar">
        <ul class="nav navbar-nav">


          <li><a class="navli" href="{% url 'propdesk:index' %}">Main</a></li>
        </ul>
          <form class="navbar-form navbar-left" role="search" action="{% url 'propdesk:search' %}" method="get">
          <div class="form-group">
              <input class="form-control" placeholder="Search Properties" type="text" name="q">
              <input class="btn btn-default" type="submit" value="Search">
          </div>
        </form>
      </div>

      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
  </nav>

propdesk/templates/propdesk/portview.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>KM Portfolio View</title>
    <link rel="stylesheet" href="{% static 'propdesk/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'propdesk/style.css' %}" />
    <script src="{% static 'propdesk/jquery-3.1.0.min.js' %}"></script>
    <script src="{% static 'propdesk/site.js' %}"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
{% include 'propdesk/nav.html' %}

    <div class="container-fluid">
        <h1> Portfolio: {{portfolio.portfolio_name}} </h1>
        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-primary">
                    <div class="panel-heading">Properties</div>
                    <div class="panel-body"></div>
                        <div class="list-group ">
                        {% for property in portfolio.property_set.all %}

                            <a class="list-group-item listitem" href="{% url 'propdesk:prop' property.id %}"> {{ property.prop_name }} </a>

                        {% endfor %}
                        </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="panel panel-primary">
                    <div class="panel-heading">Projects</div>
                    <div class="panel-body"></div>
                        <p>Will loop through all projects in all properties under this portfolio displaying several of the OLDEST uncompleted projects</p>
                </div>
            </div>
        </div>

    </div>
</body>
</html>

propdesk/templates/propdesk/project_new.html
{% extends 'propdesk/base.html' %}

{% block content %}
        <div class="panel panel-primary">
            <div class="panel-heading">New Project</div>
            <div class="panel-body propbody">
                <h1>New project</h1>
                    <form method="POST" class="project-form">{% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="save btn btn-default">Save</button>
                    </form>
            </div>
        </div>
{% endblock %}

propdesk/templates/propdesk/prop.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Waynes Wild Web</title>
    <script src="https://use.fontawesome.com/bccccab0e8.js"></script>
    <link rel="stylesheet" href="{% static 'propdesk/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'propdesk/style.css' %}" />
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="{% static 'propdesk/jquery-3.1.0.min.js' %}"></script>
    <script src="{% static 'propdesk/site.js' %}"></script>
</head>
<body>
{% include 'propdesk/nav.html' %}
<div class="container-fluid">
    <h1>{{property.prop_name}}</h1>
    <div class="row">
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-primary">
                        <div class="panel-heading">Property Information</div>
                        <div class="panel-body propbody">
                            <p>Square Feet: {{property.property_sf}}</p>
                            <p>Ownership: </p>
                            <h4>Address</h4>
                            <p> {{property.property_address}}</p>
                            <p> {{property.property_city}}, {{property.property_state}} {{property.property_zip}}</p>
                            <p> Todo: Create extended info list</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="panel panel-primary">
                        <div class="panel-heading">Tenants</div>
                        <div class="panel-body">
                            <button class="btn btn-info">Send Tenant Bulletin</button>
                            <ul class="list-group">
                            {% for tenant in property.tenant_set.all %}
                                <li class="list-group-item mainlist">
                                    <h3>{{tenant.tenant_name}}</h3>
                                    <ul class="list-group">
                                        <li class="list-group-item"> <p>Emergency Contanct: {{tenant.tenant_emergency_name}}</p><p> Phone: {{tenant.tenant_emergency_phone}}</p> <p>Email: {{tenant.tenant_emergency_email}}</p></li>
                                        <li class="list-group-item"> <p>Site Contanct: {{tenant.tenant_site_name}}</p><p> Phone: {{tenant.tenant_site_phone}}</p><p> Email: {{tenant.tenant_site_email}}</p></li>
                                    </ul>
                                    <button class="btn btn-success">Generate AAR</button><button class="btn btn-success">Generate Late Fee</button><button class="btn btn-success">Generate Invoice</button>
                                </li>
                            {% endfor %}
                            </ul>
                            <a href="{% url 'propdesk:tenant_new' %}" class="top-menu"><i class="fa fa-plus-square" aria-hidden="true"></i> New Tenant</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-primary">
                        <div class="panel-heading">On-going Projects</div>
                        <div class="panel-body">
                            <p> Projects will essentially be context specific "To Do" lists associated with property management.  It will include checkboxes like "Contract created", "Contract executed", "Invoice Paid", "CM Fee generated" </p>
                            <p> Projects will archive when complete and fall off this list.</p>

                            <ul class="list-group">
                            {% for project in property.project_set.all %}
                                <li class="list-group-item mainlist"> <strong>{{project.name}}</strong> <br> Type: {{project.type}} <br> Start-date: {{project.startdate}}</li>

                                {% endfor %}
                            </ul>
                            <a href="{% url 'propdesk:project_new' %}" class="top-menu"><i class="fa fa-plus-square" aria-hidden="true"></i> New Project</a>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="panel panel-primary">
                        <div class="panel-heading">Vendors</div>
                        <div class="panel-body">
                            <button class="btn btn-info">View all Property contracts</button>
                            <ul class="list-group">
                                {% for vendor in property.vendor_set.all %}
                                    <li class="list-group-item mainlist">
                                        <h3>{{vendor.vendor_name}}</h3>
                                        <ul class="list-group">
                                            <li class="list-group-item"> Vendor Contanct: {{vendor.vendor_contact}}, Phone: {{vendor.vendor_phone}}, Email: {{vendor.vendor_email}}</li>
                                        </ul>
                                        <button class="btn btn-success">Generate Contract</button>
                                    </li>
                                {% endfor %}
                            </ul>
                            <a href="{% url 'propdesk:vendor_new' %}" class="top-menu"><i class="fa fa-plus-square" aria-hidden="true"></i> New Vendor</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>

propdesk/templates/propdesk/search_results.html
{% extends 'propdesk/base.html' %}

{% block content %}
        <div class="panel panel-primary">
            <div class="panel-heading">Search Results</div>
            <div class="panel-body propbody">
                <p>You searched for: <strong>{{ query }}</strong></p>

                {% if properties %}
                    <p>Found {{ properties|length }} property{{ properties|pluralize }}.</p>
                    <ul class="list-group ">
                        {% for property in properties %}
                        <a class="list-group-item listitem" href="{% url 'propdesk:prop' property.id %}"> {{ property.prop_name }} </a>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>No properties matched your search criteria.</p>
                {% endif %}
            </div>
        </div>
{% endblock %}

propdesk/templates/propdesk/tenant_new.html
{% extends 'propdesk/base.html' %}

{% block content %}
<div class="panel panel-primary">
    <div class="panel-heading">New Tenant</div>
    <div class="panel-body propbody">
        <h1>New Tenant</h1>
            <form method="POST" class="tenant-form">{% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="save btn btn-default">Save</button>
            </form>
        </div>
    </div>
{% endblock %}

propdesk/templates/propdesk/vendor_new.html
{% extends 'propdesk/base.html' %}

{% block content %}
<div class="panel panel-primary">
    <div class="panel-heading">New Vendor</div>
    <div class="panel-body propbody">
        <form method="POST" class="vendor-form">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default">Save</button>
        </form>
    </div>
</div>
{% endblock %}